const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;
const MONGO_DUPLICATE_KEY_ERROR = 409;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  SERVER_ERROR,
  MONGO_DUPLICATE_KEY_ERROR,
};
